version: '3'

services:
  database:
    image: postgres
    env_file: 
      .env
    volumes:
      - demodb:/var/lib/postgresql/data
      
  api:
    image: testeapi
    build:
      context: services/rest-api
    env_file: 
      .env
    ports:
      - "8888:8080"
    depends_on:
      - database
      
volumes:
  demodb:
